### ISSUE TITLE
No support for Python 3.6

### ISSUE THREAD

**Issue by longsleep** [MarkForged/GOMP#1]
When running gomp on Ubuntu 18.04 (has Python 3.6) one is greeted with the following traceback.

```
Traceback (most recent call last):
  File "/home/longsleep/.local/bin/gomp", line 11, in <module>
    sys.exit(process_commands())
  File "/home/longsleep/.local/lib/python3.6/site-packages/gomp/gomp.py", line 320, in process_commands
    if not branch_exists(src):
  File "/home/longsleep/.local/lib/python3.6/site-packages/gomp/gomp.py", line 297, in branch_exists
    check=False,
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

This is because

> Changed in version 3.7: Added the text parameter, as a more understandable alias of universal_newlines. Added the capture_output parameter.

Python 3.6 is pretty popular - would be probably a good idea to have this supported.

**Comment by philipkiely-markforged** [comment]
Hi,

Thanks for bringing this up. You're right, I only tested on 3.7, which was an oversight.

Does this PR address your concerns? https://github.com/MarkForged/GOMP/pull/2

**Comment by longsleep** [comment]
> Does this PR address your concerns? #2

Looks about right - did not have a chance to test yet though. Thank you!

**Comment by philipkiely-markforged** [comment]
PR tested (on 3.6), approved, and merged. GOMP should support 3.6 now!

**Comment by philipkiely-markforged** [comment]
Will leave open until available on PyPi

**Comment by philipkiely-markforged** [comment]
Version 1.1, available here and on pip, should solve this issue, thanks for reporting!
