### ISSUE TITLE
Can you create a git tag (and perhaps release) for the 1.0 version, and any versions going forward?

### ISSUE THREAD

**Issue by herbygillot** [MarkForged/GOMP#6]
**Is your feature request related to a problem? Please describe.**
Would like to look at making gomp available in [MacPorts](https://www.macports.org), but there is no way to get a discrete release of the code as things currently stand.

**Describe the solution you'd like**
* A 1.0 tag in git.
* Optionally a Github release src tarball for 1.0
* ...and the above for versions going forward.

**Comment by Worty** [comment]
Im currently using the release from PyPI (https://pypi.org/project/gomp/#history) for AUR. You can use this stable download url: https://files.pythonhosted.org/packages/source/g/gomp/gomp-1.0.2.tar.gz

**Comment by philipkiely-markforged** [comment]
We have tagged a release on GitHub and updated on PyPi as well, thanks for reporting this issue.

**Comment by herbygillot** [comment]
Apologies for the lack of response: thank you, and very much appreciated.
