### ISSUE TITLE
gomp command does not support 'head' or commit hash input arguments

### ISSUE THREAD

**Issue by arikwex** [MarkForged/GOMP#7]
**Describe the bug**
The program will not acknowledge inputs such as `head` or `head~3` or `9e95411` as valid comparison markers. Since both inputs are valid commit refs, this should be an allowed comparison. In the legacy version of gomp, there was no safeguarding against existing/non-existing branches, so this was not an issue there.

**To Reproduce**
When trying to run:
```
gomp head 9e95411
```
the output will indicate that neither `head` nor `9e95411` are valid branches (which is true, they're not branches... but gomp should be able to snag any commit for its comparison view).

**Expected behavior**
Allow support for any notations that resolves to a commit rather than only branch names.

**Version and Platform**
MacOS Catalina 10.15.5
Python 3.7.0

**Comment by philipkiely-markforged** [comment]
PR merged and live, closing.
